<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class MetasDeProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '2',
            'politica_id' => '4',
            'programa_id' => '16',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR2P4MP1',
            'nombre' => 'Elaborar y promocionar el Plan Regional de Turismo a 2033',
            'indicador_meta' => 'No. de planes de turismo elaborados y promocionados',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '1',
            'meta_year_2' => '1',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '40000000',
            'recurso_year_3' => '20000000',
            'recurso_year_4' => '20000000',
            'recurso_cuatrienio' => '80000000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '2',
            'politica_id' => '4',
            'programa_id' => '16',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR2P4MP2',
            'nombre' => 'Diseño, Gestion y/o construcción de  Vias Verdes en los departamentos que componen la RAP Eje Cafetero',
            'indicador_meta' => 'No. de vías verdes diseñadas, gestionadas y/o construidas.',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '0',
            'meta_year_2' => '1',
            'meta_year_3' => '3',
            'meta_year_4' => '4',
            'meta_cuatrienio' => '4',
            'recurso_year_1' => '0',
            'recurso_year_2' => '1225000000',
            'recurso_year_3' => '421600000',
            'recurso_year_4' => '501850000',
            'recurso_cuatrienio' => '2148450000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '2',
            'politica_id' => '5',
            'programa_id' => '13',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR2P5MP1',
            'nombre' => 'Elaborar y promover la implementación del Plan Logístico Regional de la región RAP Eje Cafetero para impulsar la internacionalización de la economía',
            'indicador_meta' => 'No. de planes logísiticos elaborados y promovidos',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '1',
            'meta_year_2' => '1',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '83000000',
            'recurso_year_3' => '45000000',
            'recurso_year_4' => '45000000',
            'recurso_cuatrienio' => '173000000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '2',
            'politica_id' => '5',
            'programa_id' => '13',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR2P5MP2',
            'nombre' => 'Crear y coordinar un Tanque de Pensamiento Regional sobre movilidad, servicios e Infraestructura de la región RAP Eje Cafetero.',
            'indicador_meta' => 'No. De Tanques de Pensamiento regionales de investigación sobre infraestructura creados y coordinados',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '0',
            'meta_year_2' => '1',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '17000000',
            'recurso_year_3' => '5000000',
            'recurso_year_4' => '5000000',
            'recurso_cuatrienio' => '27000000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '2',
            'politica_id' => '5',
            'programa_id' => '14',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR2P5MP3',
            'nombre' => 'Impulsar el sistema ferroviario regional del eje cafetero y las conexiones al pacífico y el caribe.',
            'indicador_meta' => 'No. De sistemas ferroviarios regionales impulsados acompañados regionalmente',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '0',
            'meta_year_2' => '1',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '10000000',
            'recurso_year_3' => '30000000',
            'recurso_year_4' => '30000000',
            'recurso_cuatrienio' => '70000000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '2',
            'politica_id' => '5',
            'programa_id' => '15',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR2P5MP4',
            'nombre' => 'Elaborar la propuesta regional para obtener la operación del corredor vía Armenia – Pereira - Manizales en favor de la región a partir de 2027.',
            'indicador_meta' => 'No. De propuestas regionales viales elaboradas',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '1',
            'meta_year_2' => '1',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '43737371',
            'recurso_year_3' => '40000000',
            'recurso_year_4' => '40000000',
            'recurso_cuatrienio' => '123737371',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '2',
            'politica_id' => '6',
            'programa_id' => '8',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => '',
            'nombre' => 'PRODUCTO: Crear un instrumento financiero de segundo piso para la Región RAP Eje Cafetero mediante un acuerdo interinstitucional. ',
            'indicador_meta' => '',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '0',
            'meta_year_2' => '0',
            'meta_year_3' => '0',
            'meta_year_4' => '0',
            'meta_cuatrienio' => '0',
            'recurso_year_1' => '0',
            'recurso_year_2' => '0',
            'recurso_year_3' => '0',
            'recurso_year_4' => '0',
            'recurso_cuatrienio' => '0',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '2',
            'politica_id' => '6',
            'programa_id' => '24',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => '',
            'nombre' => 'PRODUCTO:  Coordinar una estrategia para la implementación del catastro  multipropósito regional. ',
            'indicador_meta' => '',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '0',
            'meta_year_2' => '0',
            'meta_year_3' => '0',
            'meta_year_4' => '0',
            'meta_cuatrienio' => '0',
            'recurso_year_1' => '0',
            'recurso_year_2' => '0',
            'recurso_year_3' => '0',
            'recurso_year_4' => '0',
            'recurso_cuatrienio' => '0',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '2',
            'politica_id' => '6',
            'programa_id' => '24',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR2P6MP1',
            'nombre' => 'Estimular y acompañar la creación y el fortalecimiento de los Esquemas Asociativos Territoriales – EAT',
            'indicador_meta' => 'No. De esquemas asociativos acompañados',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '0',
            'meta_year_2' => '1',
            'meta_year_3' => '2',
            'meta_year_4' => '0',
            'meta_cuatrienio' => '2',
            'recurso_year_1' => '0',
            'recurso_year_2' => '30000000',
            'recurso_year_3' => '30000000',
            'recurso_year_4' => '30000000',
            'recurso_cuatrienio' => '90000000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '2',
            'politica_id' => '6',
            'programa_id' => '24',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR2P6MP2',
            'nombre' => 'Fomentar y acompañar la Incorporación de un enfoque regional en los diferentes instrumentos de planificación de las entidades publicas, organizaciones de la sociedad civil y del sector privado.',
            'indicador_meta' => 'No. De enfoques regionales acompañados y fomentados',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '1',
            'meta_year_2' => '1',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '415000000',
            'recurso_year_3' => '70000000',
            'recurso_year_4' => '70000000',
            'recurso_cuatrienio' => '555000000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '2',
            'politica_id' => '6',
            'programa_id' => '20',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR2P6MP3',
            'nombre' => 'Desarrollar y liderar un programa para el fortalecimiento de la identidad regional',
            'indicador_meta' => 'No. De progranas para el fortalecimienti de la identidad regional desarrolados y liderados',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '0',
            'meta_year_2' => '1',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '10000000',
            'recurso_year_3' => '10000000',
            'recurso_year_4' => '10000000',
            'recurso_cuatrienio' => '30000000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '3',
            'politica_id' => '7',
            'programa_id' => '20',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR3P7MP1',
            'nombre' => 'Acompañar y promover la implementación del Plan de Recuperación del Parque Nacional Natural de los Nevados.',
            'indicador_meta' => 'No. de planes de recuperación acompañados y promovidos en us implementación',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '1',
            'meta_year_2' => '1',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '35000000',
            'recurso_year_3' => '17500000',
            'recurso_year_4' => '17500000',
            'recurso_cuatrienio' => '70000000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '3',
            'politica_id' => '7',
            'programa_id' => '20',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => '',
            'nombre' => '2. PRODUCTO: Acompañar la gestión del Geoparque volcán del Ruíz para la declaratoria de Geoparques Mundiales de la UNESCO. ',
            'indicador_meta' => 'No. De procesos de  acompañamiento ralizados en la gestion de una declaratoria ',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '1',
            'meta_year_2' => '1',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '35000000',
            'recurso_year_3' => '17500000',
            'recurso_year_4' => '17500000',
            'recurso_cuatrienio' => '70000000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '3',
            'politica_id' => '8',
            'programa_id' => '23',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => '',
            'nombre' => 'PRODUCTO: Crear un Sistema Regional de Información  Geográfica y Estadística y un Observatorio de Ordenamiento  Territorial Regional.',
            'indicador_meta' => '',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '0',
            'meta_year_2' => '0',
            'meta_year_3' => '0',
            'meta_year_4' => '0',
            'meta_cuatrienio' => '0',
            'recurso_year_1' => '0',
            'recurso_year_2' => '0',
            'recurso_year_3' => '0',
            'recurso_year_4' => '0',
            'recurso_cuatrienio' => '0',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '3',
            'politica_id' => '8',
            'programa_id' => '24',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR3P8MP1',
            'nombre' => 'Establecer un documento de lineamientos de planeación regional con base en la subregionalización funcional  ',
            'indicador_meta' => 'No. De documentos de lineamientos de planeación regional establecidos',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '0',
            'meta_year_2' => '1',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '15000000',
            'recurso_year_3' => '0',
            'recurso_year_4' => '0',
            'recurso_cuatrienio' => '15000000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '3',
            'politica_id' => '8',
            'programa_id' => '24',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => 'HR3P8MP2',
            'nombre' => 'Promover la implementación de un Sistema Regional de ciudades',
            'indicador_meta' => 'No. De sistemas regionales de ciudades promovidos o implementados',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '0',
            'meta_year_2' => '1',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '30000000',
            'recurso_year_3' => '30000000',
            'recurso_year_4' => '30000000',
            'recurso_cuatrienio' => '90000000',
		]);

        DB::table('meta_de_productos')->insert([
            'periodo_id' => '1',
            'hecho_id' => '3',
            'politica_id' => '8',
            'programa_id' => '25',
            'indicador_id' => '1',
            'user_id' => '1',
            'codigo' => '',
            'nombre' => '3. PRODUCTO: Asistir técnicamente la inclusión de acciones del Plan de Manejo del Paisaje Cultural Cafetero Colombiano en el Ordenamiento  Territorial y en los planes de desarrollo de los departamentos y  municipios que hacen parte de la declaratoria de la UNESCO en la RAP  EC.',
            'indicador_meta' => 'No. De planes de manejo del PCCC asisitidos tecnicamente',
            'peso' => '0',
            'linea_base' => '',
            'year' => '2021',
            'meta_year_1' => '0',
            'meta_year_2' => '0',
            'meta_year_3' => '1',
            'meta_year_4' => '1',
            'meta_cuatrienio' => '1',
            'recurso_year_1' => '0',
            'recurso_year_2' => '0',
            'recurso_year_3' => '0',
            'recurso_year_4' => '0',
            'recurso_cuatrienio' => '0',
		]);
    }
}
